# Run all extrapolations 
  
script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir) 
source("T1_correct_def_biodiv.r")
remove(list = ls())
graphics.off()

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T1_google_trends.r")
remove(list = ls())
graphics.off()   

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)         
source("T1_heard_of_biodiv.r")
remove(list = ls())
graphics.off()                       

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T2_research_studies_economic_valuation.r")
remove(list = ls())
graphics.off()

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T3_wto_green.r")
remove(list = ls())
graphics.off()

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T4_cat_1_cites_countries.r")
remove(list = ls())
graphics.off()

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T4_ecofoot.r")
remove(list = ls())
graphics.off()

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T4_HANPP.r")
remove(list = ls())
graphics.off()

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T4_trends_driven_utilisation.r")
remove(list = ls())
graphics.off()

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T4_water_footprint.r")
remove(list = ls())
graphics.off()

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T5_percent_natural_area.r")
remove(list = ls())
graphics.off()

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T5_wetland_LPI.r")
remove(list = ls())
graphics.off()

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T5_wild_bird_index.r")
remove(list = ls())
graphics.off()

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T6_MSC_certified_tonnes.r")
remove(list = ls())
graphics.off()

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T6_rli_for_seabirds.r")
remove(list = ls())
graphics.off()

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T6_Trawl_effort.r")
remove(list = ls())
graphics.off()

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T7_area_conservation_agriculture.r")
remove(list = ls())
graphics.off()

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T7_farmland_wbi.r")
remove(list = ls())
graphics.off()

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T7_fsc_pesc_certified.r")
remove(list = ls())
graphics.off()

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T7_organic_agriculture.r")
remove(list = ls())
graphics.off()

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T8_insecticide_use.r")
remove(list = ls())
graphics.off()

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T8_nitrogen_surplus.r")
remove(list = ls())
graphics.off()

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T8_rli_pollution_birds.r")
remove(list = ls())
graphics.off()

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T9_introduction_events-21countries.r")
remove(list = ls())
graphics.off()

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T9_rli_birds_alien_spp.r")
remove(list = ls())
graphics.off()

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T9_trends_invasives_legislation.r")
remove(list = ls())
graphics.off()

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T10_coral_reef_cover.r")
remove(list = ls())
graphics.off()

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T11_freshwater_ecoregion_coverage.r")
remove(list = ls())
graphics.off()

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T11_marine_ecoregion_coverage.r")
remove(list = ls())
graphics.off()

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T11_marinePA.r")
remove(list = ls())
graphics.off()

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T11_PA_coverage_spp.r")
remove(list = ls())
graphics.off()

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T11_PAME.r")
remove(list = ls())
graphics.off()

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T11_terrestrial_ecoregion_coverage.r")
remove(list = ls())
graphics.off()

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T11_terrestrialPA.r")
remove(list = ls())
graphics.off()

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T11_pa_coverage_azes.r")
remove(list = ls())
graphics.off()

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T11_pa_coverage_ibas.r")
remove(list = ls())
graphics.off()

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T12_lpi.r")
remove(list = ls())
graphics.off()

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T12_mammal_bird_extinctions.r")
remove(list = ls())
graphics.off()

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T12_lpi.r")
remove(list = ls())
graphics.off()

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T12_rli.r")
remove(list = ls())
graphics.off()

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T13_gen_div_domestic.r")
remove(lists = ls())
graphics.off()

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T14_rli_pollinators.r")
remove(list = ls())
graphics.off()

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T19_wos_biodiv_papers.r")
remove(list = ls())
graphics.off()

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T19_funds_environmental_research.r")
remove(list = ls())
graphics.off()

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T19_num_gbif_records.r")
remove(list = ls())
graphics.off()

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T20_global_funds_epl.r")
remove(list = ls())
graphics.off()

script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)
source("T20_oda_biodiv.r")

